# Generated by Django 4.0.4 on 2022-06-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_remove_answer_third_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='third_option',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
